version: '3.3'
services:
    app:
        container_name: app
        build: ./
        ports:
            - 8090:8000
        volumes:
            - ./:/var/www/html

    db:
        image: mysql
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - 3306:3306
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_USER: spallian
            MYSQL_PASSWORD: spallian
            MYSQL_DATABASE: blog
            MYSQL_ROOT_PASSWORD: root
    msphpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8086:80
        environment:
            PMA_HOST: db
